//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteServicos.ServicoAlunoServices {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Aluno", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Aluno : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeField;
        
        private int NotaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Nome {
            get {
                return this.NomeField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeField, value) != true)) {
                    this.NomeField = value;
                    this.RaisePropertyChanged("Nome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Nota {
            get {
                return this.NotaField;
            }
            set {
                if ((this.NotaField.Equals(value) != true)) {
                    this.NotaField = value;
                    this.RaisePropertyChanged("Nota");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicoAlunoServices.ServicoAlunoSoap")]
    public interface ServicoAlunoSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        ClienteServicos.ServicoAlunoServices.HelloWorldResponse HelloWorld(ClienteServicos.ServicoAlunoServices.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<ClienteServicos.ServicoAlunoServices.HelloWorldResponse> HelloWorldAsync(ClienteServicos.ServicoAlunoServices.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name CarregaAlunoResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CarregaAluno", ReplyAction="*")]
        ClienteServicos.ServicoAlunoServices.CarregaAlunoResponse CarregaAluno(ClienteServicos.ServicoAlunoServices.CarregaAlunoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CarregaAluno", ReplyAction="*")]
        System.Threading.Tasks.Task<ClienteServicos.ServicoAlunoServices.CarregaAlunoResponse> CarregaAlunoAsync(ClienteServicos.ServicoAlunoServices.CarregaAlunoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public ClienteServicos.ServicoAlunoServices.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(ClienteServicos.ServicoAlunoServices.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClienteServicos.ServicoAlunoServices.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(ClienteServicos.ServicoAlunoServices.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CarregaAlunoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CarregaAluno", Namespace="http://tempuri.org/", Order=0)]
        public ClienteServicos.ServicoAlunoServices.CarregaAlunoRequestBody Body;
        
        public CarregaAlunoRequest() {
        }
        
        public CarregaAlunoRequest(ClienteServicos.ServicoAlunoServices.CarregaAlunoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class CarregaAlunoRequestBody {
        
        public CarregaAlunoRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CarregaAlunoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CarregaAlunoResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClienteServicos.ServicoAlunoServices.CarregaAlunoResponseBody Body;
        
        public CarregaAlunoResponse() {
        }
        
        public CarregaAlunoResponse(ClienteServicos.ServicoAlunoServices.CarregaAlunoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CarregaAlunoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ClienteServicos.ServicoAlunoServices.Aluno[] CarregaAlunoResult;
        
        public CarregaAlunoResponseBody() {
        }
        
        public CarregaAlunoResponseBody(ClienteServicos.ServicoAlunoServices.Aluno[] CarregaAlunoResult) {
            this.CarregaAlunoResult = CarregaAlunoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServicoAlunoSoapChannel : ClienteServicos.ServicoAlunoServices.ServicoAlunoSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicoAlunoSoapClient : System.ServiceModel.ClientBase<ClienteServicos.ServicoAlunoServices.ServicoAlunoSoap>, ClienteServicos.ServicoAlunoServices.ServicoAlunoSoap {
        
        public ServicoAlunoSoapClient() {
        }
        
        public ServicoAlunoSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicoAlunoSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicoAlunoSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicoAlunoSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteServicos.ServicoAlunoServices.HelloWorldResponse ClienteServicos.ServicoAlunoServices.ServicoAlunoSoap.HelloWorld(ClienteServicos.ServicoAlunoServices.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            ClienteServicos.ServicoAlunoServices.HelloWorldRequest inValue = new ClienteServicos.ServicoAlunoServices.HelloWorldRequest();
            inValue.Body = new ClienteServicos.ServicoAlunoServices.HelloWorldRequestBody();
            ClienteServicos.ServicoAlunoServices.HelloWorldResponse retVal = ((ClienteServicos.ServicoAlunoServices.ServicoAlunoSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteServicos.ServicoAlunoServices.HelloWorldResponse> ClienteServicos.ServicoAlunoServices.ServicoAlunoSoap.HelloWorldAsync(ClienteServicos.ServicoAlunoServices.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteServicos.ServicoAlunoServices.HelloWorldResponse> HelloWorldAsync() {
            ClienteServicos.ServicoAlunoServices.HelloWorldRequest inValue = new ClienteServicos.ServicoAlunoServices.HelloWorldRequest();
            inValue.Body = new ClienteServicos.ServicoAlunoServices.HelloWorldRequestBody();
            return ((ClienteServicos.ServicoAlunoServices.ServicoAlunoSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteServicos.ServicoAlunoServices.CarregaAlunoResponse ClienteServicos.ServicoAlunoServices.ServicoAlunoSoap.CarregaAluno(ClienteServicos.ServicoAlunoServices.CarregaAlunoRequest request) {
            return base.Channel.CarregaAluno(request);
        }
        
        public ClienteServicos.ServicoAlunoServices.Aluno[] CarregaAluno() {
            ClienteServicos.ServicoAlunoServices.CarregaAlunoRequest inValue = new ClienteServicos.ServicoAlunoServices.CarregaAlunoRequest();
            inValue.Body = new ClienteServicos.ServicoAlunoServices.CarregaAlunoRequestBody();
            ClienteServicos.ServicoAlunoServices.CarregaAlunoResponse retVal = ((ClienteServicos.ServicoAlunoServices.ServicoAlunoSoap)(this)).CarregaAluno(inValue);
            return retVal.Body.CarregaAlunoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteServicos.ServicoAlunoServices.CarregaAlunoResponse> ClienteServicos.ServicoAlunoServices.ServicoAlunoSoap.CarregaAlunoAsync(ClienteServicos.ServicoAlunoServices.CarregaAlunoRequest request) {
            return base.Channel.CarregaAlunoAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteServicos.ServicoAlunoServices.CarregaAlunoResponse> CarregaAlunoAsync() {
            ClienteServicos.ServicoAlunoServices.CarregaAlunoRequest inValue = new ClienteServicos.ServicoAlunoServices.CarregaAlunoRequest();
            inValue.Body = new ClienteServicos.ServicoAlunoServices.CarregaAlunoRequestBody();
            return ((ClienteServicos.ServicoAlunoServices.ServicoAlunoSoap)(this)).CarregaAlunoAsync(inValue);
        }
    }
}
